### ISSUE TITLE
Error 400 from Grafana to InfluxDB datasource

### ISSUE THREAD

**Issue by mtthidoteu** [acouvreur/ssh-log-to-influx#158]
Hey guys!
I'm having a bit of a problem with Grafana and InfluxDB. Everything works but I can't get grafana to connect to InfluxDB. It is really weird but I'm getting an Network Error 400.

```
version: "3.7"

services:
  ssh-log-to-influx:
    image: acouvreur/ssh-log-to-influx:latest
    build: ./
    restart: always
    user: 1000:1000
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_DB=telegraf
    ports:
      - 7070:7070/tcp
    networks:
      - default

  #----------------------------------------------#
  # InfluxDB : time series database
  #----------------------------------------------#
  influxdb:
    image: influxdb:latest
    user: 1000:1000
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    networks:
      - default
    
  # Grafana : analytics and monitoring
  #----------------------------------------------#
  grafana:
    image: "grafana/grafana:latest"
    user: 1000:1000
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,grafana-piechart-panel
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - default
      - web

networks:
  default:
  web:
    name: web
```

Any pointers would be really appreaciated!
