### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by ghost** [acouvreur/ssh-log-to-influx#45]
What is the exact syntax for docker-compose.yml? For a configuration of influxdb on another server.

```
version: "3.7"

services:
  ssh-log-to-influx:
    image: acouvreur/ssh-log-to-influx
    build: ./
    restart: always
    environment:
      - INFLUX_URL=https://mydomain:8086
      - INFLUX_DB=mydb
      - INFLUX_USER=myuser
      - INFLUX_PWD=mystrongpassword
    ports:
      - 7070:7070/tcp
```

With this configuration the container restarts all the time.

**Comment by acouvreur** [comment]
Hi, the exact syntax is configured by the following environment variables : 

- INFLUX_URL : the FQDN part only (so no HTTP and no port)
- INFLUX_PROTOCOL : 'http' or 'https'

It is indeed pretty unclear, I will update this ASAP to provide a more detailed configuration !

```
version: "3.7"

services:
  ssh-log-to-influx:
    image: acouvreur/ssh-log-to-influx
    build: ./
    restart: always
    environment:
      - INFLUX_URL=mydomain
      - INFLUX_DB=mydb
      - INFLUX_USER=myuser
      - INFLUX_PWD=mystrongpassword
      - INFLUX_PORT=https
    ports:
      - 7070:7070/tcp
```

would be valid. Can you try it ? Thanks.
